services:
  mariadb:
    container_name: mariadb
    # We use a mariadb image which supports both amd64 & arm64 architecture
    image: mariadb:10-focal
    # If you really want to use MySQL, uncomment the following line
    #image: mysql:8
    secrets:
      - db-password
    volumes:
      - ./db/initdb:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=household-accounts
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 3306

  backend:
    container_name: backend
    build: ./backend
    volumes:
      - ./backend:/var/www/backend
    secrets:
      - db-password
    depends_on:
      - mariadb

  nginx:
    container_name: nginx
    image: nginx
    environment:
      TZ: 'Azia/Tokyo'
    ports:
      - 80:80
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/log:/var/log/nginx
    depends_on:
      - backend

volumes:
  db-data:

secrets:
  db-password:
    file: db/password.txt
